import { Enum } from 'enum-plus';
export const FoodTemperatureEnum = Enum({
  Cold: { value: -1, label: '冷食' },
  Hot: { value: 1, label: '热食' },
});

export const FoodTypeEnum = Enum({
  Generic: { value: 0, label: '通用' },
  Elemental: { value: 1, label: '元素(非冒险家食物)' },
  Meat: { value: 2, label: '肉' },
  Veggie: { value: 3, label: '素食' },
  Roughage: { value: 4, label: '粗食(非冒险家食物)' },
  Goodies: { value: 5, label: '好东西' },
  Monster: { value: 6, label: '怪物(非冒险家食物)' },
  Wood: { value: 7, label: '木质(非冒险家食物)' },
});
type FoodTemperatureType = typeof FoodTemperatureEnum.valueType;
type FoodType = typeof FoodTypeEnum.valueType;
export interface Cooking {
  id: string;
  name: string;
  cname: string;
  imgPath: string;
  foodType?: FoodType | FoodType[];
  expired?: number;
  temperatureType?: FoodTemperatureType;
  dimension: [number | string, number | string, number | string];
  getWays: string;
  waysQuery?: string | string[];
  code: string;
  style?: React.CSSProperties;
  description?: string;
}

export const cookingList: Cooking[] = [
  {
    id: 'Amberosia_Dropped',
    name: 'Amberosia',
    cname: '琥珀美食',
    foodType: FoodTypeEnum.Elemental,
    imgPath: '/images/cooking/Amberosia_Dropped.webp',
    dimension: [12.5, 10, 0],
    code: '"dustmeringue"',
    waysQuery: '尘土块',
    getWays:
      '琥珀美食可以由烹饪产生。烹饪配方为：至少 1 个尘土块。优先级为 100（其它 3 格无论放任何食材都会烹饪出琥珀美食），需要花费 40 秒。',
  },
  {
    id: 'Asparagazpacho_Dropped',
    name: 'Asparagazpacho',
    cname: '芦笋冷汤',
    foodType: FoodTypeEnum.Veggie,
    expired: 15,
    imgPath: '/images/cooking/Asparagazpacho_Dropped.webp',
    dimension: [25, 3, 10],
    temperatureType: FoodTemperatureEnum.Cold,
    waysQuery: ['大厨特色菜', '沃利', '便携烹饪锅'],
    code: '"gazpacho"',
    getWays:
      '芦笋冷汤属于大厨特色菜，它只能由沃利使用便携烹饪锅烹饪，配方为：至少 2 个芦笋/烤芦笋，冰度大于等于 2。优先级为 30，需要花费 10 秒，但由于便携烹饪锅会减少 20% 烹饪时间，实际烹饪时间为 8 秒。',
  },
  {
    id: 'Asparagus_Soup_Dropped',
    name: 'Asparagus Soup',
    cname: '芦笋汤',
    expired: 15,
    dimension: [18.75, 20, 5],
    foodType: FoodTypeEnum.Veggie,
    getWays:
      '芦笋汤只能由烹饪产生。烹饪配方为：至少有 1 个芦笋/烤芦笋，蔬菜度大于 2，不能有肉度和不可食用度。优先级为 10，需要花费 10 秒。',
    waysQuery: ['芦笋/烤芦笋', '蔬菜度', '肉度', '不可食用度'],
    code: '	"asparagussoup"',
    imgPath: '/images/cooking/Asparagus_Soup_Dropped.webp',
    style: { objectFit: 'cover' },
  },
  {
    id: 'Bacon_and_Eggs_Dropped',
    name: 'Bacon and Eggs',
    cname: '培根煎蛋',
    foodType: FoodTypeEnum.Meat,
    expired: 20,
    dimension: [75, 20, 5],
    getWays: '培根煎蛋只能由烹饪产生。烹饪配方为：肉度大于 1，蛋度大于 1，没有蔬菜度。优先级为 10，需要花费 40 秒。',
    waysQuery: ['肉度', '蛋度', '蔬菜度'],
    code: '"baconeggs"',
    imgPath: '/images/cooking/Bacon_and_Eggs_Dropped.webp',
  },
  {
    id: 'Banana_Pop_Dropped',
    name: 'Banana Pop',
    cname: '香蕉冻',
    foodType: FoodTypeEnum.Veggie,
    imgPath: '/images/cooking/Banana_Pop_Dropped.webp',
    temperatureType: FoodTemperatureEnum.Cold,
    dimension: [12.5, 20, 33],
    expired: 3,
    getWays:
      '香蕉冻能由烹饪产生。烹饪配方为：至少 1 个香蕉/熟香蕉，至少 1 个树枝，冰度大于 0，没有肉度和鱼度，优先级为 20，需要花费 10 秒。香蕉冻还能通过与小丑进行卡牌游戏获取。',
    waysQuery: ['香蕉/熟香蕉', '树枝', '冰度', '肉度', '鱼度', '小丑'],
    code: '	"bananapop"',
  },
  {
    id: 'Banana_Shake_Dropped',
    name: 'Banana Shake',
    cname: '香蕉奶昔',
    imgPath: '/images/cooking/Banana_Shake_Dropped.webp',
    expired: 15,
    foodType: FoodTypeEnum.Veggie,
    dimension: [25, 8, 33],
    getWays:
      '香蕉奶昔可以从烹饪产生。烹饪配方为：至少 2 个香蕉/熟香蕉，不能有肉度、鱼度、怪物度。优先级为 1，需要花费 10 秒。',
    waysQuery: ['香蕉/熟香蕉', '肉度', '鱼度', '怪物度'],
    code: '"bananajuice"',
  },
  {
    id: 'Barnacle_Linguine_Dropped',
    name: 'Barnacle Linguine',
    cname: '藤壶中细面',
    imgPath: '/images/cooking/Barnacle_Linguine_Dropped.webp',
    expired: 6,
    dimension: [75, 30, 20],
    foodType: FoodTypeEnum.Meat,
    getWays:
      '藤壶中细面只能由烹饪产生。烹饪配方为：至少有 2 个藤壶/熟藤壶，蔬菜度大于等于 2。优先级为 30，需要花费 40 秒来制作。',
    waysQuery: ['藤壶/熟藤壶', '蔬菜度'],
    code: '"barnaclinguine"',
  },
  {
    id: 'Barnacle_Nigiri_Dropped',
    name: 'Barnacle Nigiri',
    cname: '藤壶握寿司',
    imgPath: '/images/cooking/Barnacle_Nigiri_Dropped.webp',
    dimension: [37.5, 40, 15],
    foodType: FoodTypeEnum.Meat,
    expired: 10,
    getWays:
      '藤壶握寿司只能由烹饪产生。烹饪配方为：至少有 1 个藤壶/熟藤壶，海带叶/熟海带叶，蛋度大于等于 1。优先级为 30，需要花费 10 秒。',
    waysQuery: ['藤壶/熟藤壶', '海带叶/熟海带叶', '蛋度'],
    code: '	"barnaclesushi"',
  },
  {
    id: 'Barnacle_Pita_Dropped',
    name: 'Barnacle Pita',
    cname: '藤壶皮塔饼',
    imgPath: '/images/cooking/Barnacle_Pita_Dropped.webp',
    foodType: FoodTypeEnum.Meat,
    expired: 15,
    dimension: [37.5, 20, 5],
    getWays:
      '藤壶皮塔饼只能由烹饪产生。烹饪配方为：至少有 1 个藤壶/熟藤壶，蔬菜度大于等于 0.5。优先级为 25，需要花费 40 秒。',
    waysQuery: ['藤壶/熟藤壶', '蔬菜度'],
    code: '"barnaclepita"',
    style: { objectFit: 'cover' },
  },
  {
    id: 'Beefalo_Treats_Dropped',
    name: 'Beefalo Treats',
    cname: '皮弗娄牛零食',
    imgPath: '/images/cooking/Beefalo_Treats_Dropped.webp',
    foodType: FoodTypeEnum.Roughage,
    dimension: [25, 75, 0],
    expired: 20,
    getWays:
      '皮弗娄牛零食只能由烹饪产生。烹饪配方为：至少 1 个必忘我，不可食用度大于 0，种子度大于 0，不能有怪物度、肉度、鱼度、蛋度、油脂度、乳制品度和魔法度。优先级为 -4，需要花费 40 秒。',
    waysQuery: ['必忘我', '不可食用度', '种子度', '肉度', '鱼度', '蛋度', '油脂度', '乳制品度', '魔法度'],
    code: '"beefalotreat"',
  },
  {
    id: 'Beefy_Greens_Dropped',
    name: 'Beefy Greens',
    cname: '牛肉绿叶菜',
    imgPath: '/images/cooking/Beefy_Greens_Dropped.webp',
    foodType: FoodTypeEnum.Meat,
    expired: 6,
    dimension: [75, 40, 5],
    getWays:
      '牛肉绿叶菜只能由烹饪产生。烹饪配方为：至少 1 个叶肉/烤叶肉，蔬菜度大于等于 3。优先级为 25，需要花费 40 秒。',
    waysQuery: ['叶肉/烤叶肉', '蔬菜度'],
    code: '	"meatysalad"',
    style: { objectFit: 'cover' },
  },
  {
    id: 'Bone_Bouillon_Dropped',
    name: 'Bone Bouillon',
    cname: '骨头汤',
    imgPath: '/images/cooking/Bone_Bouillon_Dropped.webp',
    foodType: FoodTypeEnum.Meat,
    expired: 10,
    dimension: [75, 20, 5],
    getWays:
      '骨头汤属于大厨特色菜，只能由沃利使用便携烹饪锅烹饪，配方为：恰好 2 个骨头碎片、至少 1 个洋葱/烤洋葱，不可食用度小于 3 。优先级为 30，需要花费 40 秒，但由于便携烹饪锅减少 20% 烹饪时间，实际烹饪时间为 32 秒。',
    waysQuery: ['大厨特色菜', '沃利', '便携烹饪锅', '骨头碎片', '洋葱/烤洋葱', '不可食用度'],
    code: '"bonesoup"',
  },
  {
    id: 'Breakfast_Skillet_Dropped',
    name: 'Breakfast Skillet',
    cname: '早餐锅',
    imgPath: '/images/cooking/Breakfast_Skillet_Dropped.webp',
    foodType: FoodTypeEnum.Meat,
    expired: 20,
    dimension: [75, 20, 5],
    getWays:
      '早餐锅只能由烹饪产生。烹饪配方为：蛋度大于等于 1，蔬菜度大于等于 1，没有肉度和乳制品度。优先级为 1，需要花费 20 秒。',
    waysQuery: ['蛋度', '蔬菜度', '肉度', '乳制品度'],
    code: '	"veggieomlet"',
  },
  {
    id: 'Bunny_Stew_Dropped',
    name: 'Bunny Stew',
    cname: '炖兔子',
    imgPath: '/images/cooking/Bunny_Stew_Dropped.webp',
    temperatureType: FoodTemperatureEnum.Hot,
    expired: 10,
    foodType: FoodTypeEnum.Meat,
    dimension: [37.5, 20, 5],
    getWays:
      '炖兔子只能由烹饪产生。烹饪配方为：肉度大于 0 且小于 1，冰度大于等于 2，没有不可食用度。优先级为 1，需要花费 10 秒来制作。',
    waysQuery: ['肉度', '冰度', '不可食用度'],
    code: '	"bunnystew"',
  },
  {
    id: 'Butter_Muffin_Dropped',
    name: 'Butter Muffin',
    cname: '蝴蝶松饼',
    imgPath: '/images/cooking/Butter_Muffin_Dropped.webp',
    foodType: FoodTypeEnum.Veggie,
    dimension: [37.5, 20, 5],
    expired: 15,
    getWays:
      '蝴蝶松饼只能由烹饪产生。烹饪配方为：至少有 1 个蝴蝶翅膀/月蛾翅膀，蔬菜度大于等于 0.5，没有肉度。优先级为 1，需要花费 40 秒。',
    waysQuery: ['蝴蝶翅膀/月蛾翅膀', '蔬菜度', '肉度'],
    code: '	"butterflymuffin"',
  },
  {
    id: 'California_Roll_Dropped',
    name: 'California Roll',
    cname: '加州卷',
    imgPath: '/images/cooking/California_Roll_Dropped.webp',
    foodType: FoodTypeEnum.Meat,
    expired: 10,
    dimension: [37.5, 20, 10],
    getWays:
      '加州卷只能由烹饪产生。烹饪配方为：鱼度大于等于 1，恰好 2 个海带叶/熟海带叶/干海带叶。优先级为 20，需要花费 10 秒。',
    waysQuery: ['鱼度', '海带叶/熟海带叶/干海带叶'],
    code: '	"californiaroll"',
    style: { objectFit: 'cover' },
  },
  {
    id: 'Ceviche_Dropped',
    name: 'Ceviche',
    cname: '酸橘汁腌鱼',
    imgPath: '/images/cooking/Ceviche_Dropped.webp',
    temperatureType: FoodTemperatureEnum.Cold,
    expired: 10,
    foodType: FoodTypeEnum.Meat,
    dimension: [20, 20, 5],
    getWays:
      '酸橘汁腌鱼只能由烹饪产生。烹饪配方为：鱼度大于等于 2，冰度大于 0，不能有蛋度和不可食用度。优先级为 20，需要花费 10 秒。',
    waysQuery: ['鱼度', '冰度', '蛋度', '不可食用度'],
    code: '"ceviche"',
    style: { objectFit: 'cover' },
  },
  {
    id: 'Creamy_Potato_Purée_Dropped',
    name: 'Creamy Potato Purée',
    cname: '奶油土豆泥',
    imgPath: '/images/cooking/Creamy_Potato_Purée_Dropped.webp',
    foodType: FoodTypeEnum.Veggie,
    expired: 15,
    dimension: [37.5, 20, 33],
    getWays:
      '奶油土豆泥只能由烹饪产生。烹饪配方为：至少 2 个土豆/烤土豆，至少 1 个大蒜/烤大蒜，没有肉度和不可食用度。优先级为 20，需要花费 20 秒。',
    waysQuery: ['土豆/烤土豆', '大蒜/烤大蒜', '肉度', '不可食用度'],
    code: '"mashedpotatoes"',
    style: { objectFit: 'cover' },
  },
  {
    id: 'Dragonpie_Dropped',
    name: 'Dragonpie',
    cname: '火龙果派',
    imgPath: '/images/cooking/Dragonpie_Dropped.webp',
    temperatureType: FoodTemperatureEnum.Hot,
    expired: 15,
    foodType: FoodTypeEnum.Veggie,
    dimension: [75, 40, 5],
    getWays: '火龙果派能由烹饪产生。烹饪配方为：至少有 1 个火龙果/烤火龙果，没有肉度。优先级为 1，需要花费 40 秒。',
    waysQuery: ['火龙果/烤火龙果', '肉度'],
    code: '	"dragonpie"',
  },
  {
    id: 'Fancy_Spiralled_Tubers_Dropped',
    name: 'Fancy Spiralled Tubers',
    cname: '花式回旋块茎',
    imgPath: '/images/cooking/Fancy_Spiralled_Tubers_Dropped.webp',
    foodType: FoodTypeEnum.Veggie,
    expired: 10,
    dimension: [37.5, 3, 15],
    getWays:
      '花式回旋块茎只能由烹饪产生。烹饪配方为：至少 1 个土豆/烤土豆，至少 1 个树枝，怪物度小于等于 1，不可食用度小于等于 2，不能有肉度。优先级为 10，需要花费 15 秒。',
    waysQuery: ['土豆/烤土豆', '树枝', '怪物度', '不可食用度', '肉度'],
    code: '	"potatotornado"',
  },
  {
    id: 'Fig-Stuffed_Trunk_Dropped',
    name: 'Fig-Stuffed Trunk',
    cname: '无花果酿象鼻',
    imgPath: '/images/cooking/Fig-Stuffed_Trunk_Dropped.webp',
    foodType: FoodTypeEnum.Meat,
    dimension: [150, 60, 15],
    expired: 15,
    getWays:
      '无花果酿象鼻只能由烹饪产生。烹饪配方为：至少有 1 个无花果/熟无花果，至少有 1 个象鼻/冬象鼻/象鼻排。优先级为 40，需要花费 40 秒。',
    waysQuery: ['无花果/熟无花果', '象鼻/冬象鼻/象鼻排'],
    code: '"koalefig_trunk"',
  },
  {
    id: 'Figatoni_Dropped',
    name: 'Figatoni',
    cname: '无花果意面',
    imgPath: '/images/cooking/Figatoni_Dropped.webp',
    dimension: [56.25, 30, 15],
    expired: 15,
    foodType: FoodTypeEnum.Meat,
    getWays:
      '无花果意面只能由烹饪产生。烹饪配方为：至少有 1 个无花果/熟无花果，蔬菜度大于等于 2，没有肉度。优先级为 30，需要花费 40 秒。',
    waysQuery: ['无花果/熟无花果', '蔬菜度', '肉度'],
    code: '	"figatoni"',
  },
  {
    id: 'Figgy_Frogwich_Dropped',
    name: 'Figgy Frogwich',
    cname: '无花果蛙腿三明治',
    imgPath: '/images/cooking/Figgy_Frogwich_Dropped.webp',
    foodType: FoodTypeEnum.Meat,
    temperatureType: FoodTemperatureEnum.Hot,
    dimension: [25, 20, 5],
    expired: 15,
    getWays:
      '无花果蛙腿三明治只能由烹饪产生。烹饪配方为：至少 1 个无花果/熟无花果，至少 1 个蛙腿或烤蛙腿。优先级为 1，需要花费 20 秒。',
    waysQuery: ['无花果/熟无花果', '蛙腿', '烤蛙腿'],
    code: '"frognewton"',
  },
  {
    id: 'Figkabab_Dropped',
    name: 'Figkabab',
    cname: '无花果烤串',
    imgPath: '/images/cooking/Figkabab_Dropped.webp',
    temperatureType: FoodTemperatureEnum.Hot,
    foodType: FoodTypeEnum.Meat,
    dimension: [37.5, 20, 10],
    expired: 15,
    getWays:
      '无花果烤串只能由烹饪产生。烹饪配方为：至少有 1 个无花果/熟无花果，至少有 1 个树枝，肉度大于等于 1，怪物度小于等于 1。优先级为 30，需要花费 20 秒。',
    waysQuery: ['无花果/熟无花果', '树枝', '肉度', '怪物度'],
    code: '"figkabab"',
  },
  {
    id: 'Fish_Cordon_Bleu_Dropped',
    name: 'Fish Cordon Bleu',
    cname: '蓝带鱼排',
    imgPath: '/images/cooking/Fish_Cordon_Bleu_Dropped.webp',
    foodType: FoodTypeEnum.Meat,
    dimension: [37.5, 20, -10],
    expired: 8,
    getWays:
      '蓝带鱼排属于大厨特色菜，只能由沃利使用便携烹饪锅烹饪，配方为：至少 2 个蛙腿/烤蛙腿、鱼度大于等于 1 ，没有不可食用度。优先级为 30，需要花费 40 秒，但由于便携烹饪锅减少 20% 烹饪时间，实际烹饪时间为 32 秒。',
    waysQuery: ['大厨特色菜', '沃利', '便携烹饪锅', '蛙腿/烤蛙腿', '鱼度', '不可食用度'],
    code: '	"frogfishbowl"',
  },
  {
    id: 'Fish_Tacos_Dropped',
    name: 'Fish Tacos',
    cname: '鱼肉玉米卷',
    imgPath: '/images/cooking/Fish_Tacos_Dropped.webp',
    foodType: FoodTypeEnum.Meat,
    expired: 6,
    dimension: [37.5, 20, 5],
    getWays:
      '鱼肉玉米卷只能由烹饪产生。烹饪配方为：至少有 1 个玉米/爆米花/爆米花鱼/玉米鳕鱼，鱼度大于 0。优先级为 10，需要花费 10 秒。',
    waysQuery: ['玉米/爆米花/爆米花鱼/玉米鳕鱼', '鱼度'],
    code: '	"fishtacos"',
  },
  {
    id: 'Fishsticks_Dropped',
    name: 'Fishsticks',
    cname: '炸鱼排',
    imgPath: '/images/cooking/Fishsticks_Dropped.webp',
    foodType: FoodTypeEnum.Meat,
    expired: 10,
    dimension: [37.5, 40, 5],
    getWays:
      '炸鱼排只能由烹饪产生。烹饪配方为：至少有 1 个树枝，鱼度大于 0，不可食用度大于 0 且小于等于 1。优先级为 10，需要花费 40 秒。',
    waysQuery: ['树枝', '鱼度', '不可食用度'],
    code: '"fishsticks"',
  },
  {
    id: 'Fist_Full_of_Jam_Dropped',
    name: 'Fist Full of Jam',
    cname: '果酱',
    imgPath: '/images/cooking/Fist_Full_of_Jam_Dropped.webp',
    foodType: FoodTypeEnum.Veggie,
    expired: 15,
    dimension: [37.5, 3, 5],
    getWays: '果酱只能由烹饪产生。烹饪配方为：水果度大于 0，没有肉度、蔬菜度和不可食用度。优先级为 0，需要花费 10 秒。',
    waysQuery: ['水果度', '肉度', '蔬菜度', '不可食用度'],
    code: '	"jammypreserves"',
    style: { objectFit: 'cover' },
  },
  {
    id: 'Flower_Salad_Dropped',
    name: 'Flower Salad',
    cname: '花沙拉',
    imgPath: '/images/cooking/Flower_Salad_Dropped.webp',
    foodType: FoodTypeEnum.Veggie,
    expired: 6,
    dimension: [12.5, 40, 5],
    getWays:
      '花沙拉只能由烹饪产生。烹饪配方为：至少 1 个仙人掌花，蔬菜度大于等于 2，不包含肉度、不可食用度、蛋度、甜味剂度、水果度。优先级为10，需要花费10秒。',
    waysQuery: ['蔬菜度', '仙人掌花', '水果度', '肉度', '不可食用度', '蛋度', '甜味剂度'],
    code: '	"flowersalad"',
  },
  {
    id: 'Fresh_Fruit_Crepes_Dropped',
    name: 'Fresh Fruit Crepes',
    cname: '鲜果可丽饼',
    imgPath: '/images/cooking/Fresh_Fruit_Crepes_Dropped.webp',
    dimension: [150, 50, 15],
    expired: 10,
    foodType: FoodTypeEnum.Veggie,
    getWays:
      '鲜果可丽饼属于大厨特色菜，只能由沃利使用便携烹饪锅烹饪，配方为：至少 1 个蜂蜜，至少 1 个黄油，水果度大于等于 1.5。优先级为 30，需要花费 40 秒，但由于便携烹饪锅减少 20% 烹饪时间，实际烹饪时间为 32 秒。',
    waysQuery: ['大厨特色菜', '沃利', '便携烹饪锅', '蜂蜜', '黄油', '水果度'],
    code: '	"freshfruitcrepes"',
    style: { objectFit: 'cover' },
  },
  {
    id: 'Froggle_Bunwich_Dropped',
    name: 'Froggle Bunwich',
    cname: '蛙腿三明治',
    imgPath: '/images/cooking/Froggle_Bunwich_Dropped.webp',
    dimension: [37.5, 20, 5],
    foodType: FoodTypeEnum.Meat,
    expired: 15,
    getWays:
      '蛙腿三明治只能由烹饪产生。烹饪配方为：至少有 1 个蛙腿/烤蛙腿，蔬菜度大于等于 0.5。优先级为 1，需要花费 40 秒。',
    waysQuery: ['蛙腿/烤蛙腿', '蔬菜度'],
    code: '"frogglebunwich"',
  },
  {
    id: 'Frozen_Banana_Daiquiri_Dropped',
    name: 'Frozen Banana Daiquiri',
    cname: '冰香蕉冻唇蜜',
    imgPath: '/images/cooking/Frozen_Banana_Daiquiri_Dropped.webp',
    temperatureType: FoodTemperatureEnum.Cold,
    foodType: FoodTypeEnum.Goodies,
    dimension: [18.75, 30, 15],
    expired: 15,
    getWays:
      '冰香蕉冻唇蜜可由烹饪产生。烹饪配方为：至少有 1 个香蕉/熟香蕉，冰度大于等于 1，不能有肉度、鱼度。优先级为 2，需要花费 20 秒。',
    waysQuery: ['香蕉/熟香蕉', '冰度', '肉度', '鱼度'],
    code: '	"frozenbananadaiquiri"',
  },
  {
    id: 'Fruit_Medley_Dropped',
    name: 'Fruit Medley',
    cname: '水果圣代',
    imgPath: '/images/cooking/Fruit_Medley_Dropped.webp',
    temperatureType: FoodTemperatureEnum.Cold,
    dimension: [25, 20, 5],
    expired: 6,
    foodType: FoodTypeEnum.Veggie,
    getWays: '水果圣代只能由烹饪产生。烹饪配方为：水果度大于等于 3，没有肉度、蔬菜度。优先级为 0，需要花费 10',
    waysQuery: ['水果度', '肉度', '蔬菜度'],
    code: '	"fruitmedley"',
  },
  {
    id: 'Glow_Berry_Mousse_Dropped',
    name: 'Glow Berry Mousse',
    cname: '发光浆果慕斯',
    imgPath: '/images/cooking/Glow_Berry_Mousse_Dropped.webp',
    foodType: FoodTypeEnum.Meat,
    dimension: [37.5, 3, 10],
    expired: 8,
    getWays:
      '发光浆果慕斯属于大厨特色菜，只能由沃利使用便携烹饪锅烹饪，配方为：至少 2 个小发光浆果或至少 1 个发光浆果，水果度大于等于 2，不能有不可食用度和肉度 。优先级为 30，需要花费 20 秒，但由于便携烹饪锅减少 20% 烹饪时间，实际烹饪时间为 16 秒。',
    waysQuery: [
      '发光浆果慕斯',
      '大厨特色菜',
      '沃利',
      '便携烹饪锅',
      '小发光浆果',
      '发光浆果',
      '水果度',
      '不可食用度',
      '肉度',
    ],
    code: '"glowberrymousse"',
  },
  {
    id: 'Grim_Galette_Dropped',
    name: 'Grim Galette',
    cname: '恐怖国王饼',
    imgPath: '/images/cooking/Grim_Galette_Dropped.webp',
    foodType: FoodTypeEnum.Veggie,
    dimension: [25, 1, 5],
    expired: 10,
    getWays:
      '恐怖国王饼属于大厨特色菜，只能由沃利使用便携烹饪锅烹饪，配方为：恰好 2 个噩梦燃料、1 个洋葱/烤洋葱和 1 个土豆/烤土豆 。优先级为 30，需要花费 40 秒来制作，但由于便携烹饪锅减少 20% 烹饪时间，所以实际烹饪时间为 32 秒。',
    waysQuery: ['大厨特色菜', '沃利', '便携烹饪锅', '噩梦燃料', '洋葱/烤洋葱', '土豆/烤土豆'],
    code: '"nightmarepie"',
  },
  {
    id: 'Guacamole_Dropped',
    name: 'Guacamole',
    cname: '鳄梨酱',
    imgPath: '/images/cooking/Guacamole_Dropped.webp',
    foodType: FoodTypeEnum.Meat,
    expired: 10,
    dimension: [37.5, 20, 0],
    getWays:
      '鳄梨酱只能由烹饪产生。烹饪配方为：至少 1 个鼹鼠，至少 1 个仙人掌肉/成熟石果，不包含水果度。优先级为 10，需要花费 10 秒。',
    waysQuery: ['鼹鼠', '仙人掌肉/成熟石果', '水果度'],
    code: '"guacamole"',
  },
  {
    id: 'Honey_Ham_Dropped',
    name: 'Honey Ham',
    cname: '蜜汁火腿',
    imgPath: '/images/cooking/Honey_Ham_Dropped.webp',
    temperatureType: FoodTemperatureEnum.Hot,
    foodType: FoodTypeEnum.Meat,
    dimension: [75, 30, 5],
    expired: 15,
    getWays:
      '蜜汁火腿只能由烹饪产生。烹饪配方为：至少有 1 个蜂蜜，肉度大于 1.5，没有不可食用度。优先级为 2，需要花费 40 秒。',
    waysQuery: ['蜂蜜', '肉度', '不可食用度'],
    code: '"honeyham"',
  },
  {
    id: 'Honey_Nuggets_Dropped',
    name: 'Honey Nuggets',
    cname: '蜜汁卤肉',
    imgPath: '/images/cooking/Honey_Nuggets_Dropped.webp',
    foodType: FoodTypeEnum.Meat,
    expired: 15,
    dimension: [37.5, 20, 5],
    getWays:
      '蜜汁卤肉只能由烹饪产生，制作配方为：至少 1 个蜂蜜，肉度大于 0 小于等于 1.5，没有不可食用度。优先级为 2，需要花费 40 秒。',
    waysQuery: ['蜂蜜', '肉度', '不可食用度'],
    code: '"honeynuggets"',
  },
  {
    id: 'Hot_Dragon_Chili_Salad_Dropped',
    name: 'Hot Dragon Chili Salad',
    cname: '辣龙椒沙拉',
    imgPath: '/images/cooking/Hot_Dragon_Chili_Salad_Dropped.webp',
    temperatureType: FoodTemperatureEnum.Hot,
    foodType: FoodTypeEnum.Veggie,
    dimension: [25, -3, 10],
    expired: 15,
    getWays:
      '辣龙椒沙拉属于大厨特色菜食谱，它只能由沃利使用便携烹饪锅烹饪，配方为：至少有一个火龙果/烤火龙果、至少有一个辣椒/烤辣椒，不能有肉度、不可食用度、蛋度。优先级为30，需要花费 15 秒来制作，由于便携烹饪锅减少 20% 烹饪时间，所以实际烹饪时间为 12 秒。',
    waysQuery: ['大厨特色菜', '沃利', '便携烹饪锅', '火龙果/烤火龙果', '辣椒/烤辣椒', '肉度', '不可食用度', '蛋度'],
    code: '"dragonchilisalad"',
    style: { objectFit: 'cover' },
  },
  {
    id: 'Ice_Cream_Dropped',
    name: 'Ice Cream',
    cname: '冰淇淋',
    imgPath: '/images/cooking/Ice_Cream_Dropped.webp',
    temperatureType: FoodTemperatureEnum.Cold,
    foodType: FoodTypeEnum.Goodies,
    dimension: [25, 0, 50],
    expired: 3,
    getWays:
      '冰淇淋只能由烹饪产生。烹饪配方为：甜味剂度、冰度和乳制品度大于 0，且没有肉度、蔬菜度、不可食用度和蛋度，优先级为 10，需要花费 10 秒。',
    waysQuery: ['甜味剂度', '冰度', '乳制品度', '肉度', '蔬菜度', '不可食用度', '蛋度'],
    code: '	"icecream"',
    style: { objectFit: 'cover' },
  },
  {
    id: 'Jelly_Salad_Dropped',
    name: 'Jelly Salad',
    cname: '果冻沙拉',
    imgPath: '/images/cooking/Jelly_Salad_Dropped.webp',
    foodType: FoodTypeEnum.Meat,
    dimension: [37.5, 0, 50],
    expired: 6,
    getWays:
      '果冻沙拉只能由烹饪产生。烹饪配方为：至少 2 个叶肉/烤叶肉，甜味剂度大于等于 2。优先级为 50，需要花费 40 秒。',
    waysQuery: ['叶肉/烤叶肉', '甜味剂度'],
    code: '	"leafymeatsouffle"',
    style: { objectFit: 'cover' },
  },
  {
    id: 'Jellybeans_Dropped',
    name: 'Jellybeans',
    cname: '彩虹糖豆',
    imgPath: '/images/cooking/Jellybeans_Dropped.webp',
    foodType: FoodTypeEnum.Goodies,
    dimension: [0, 2, 5],
    getWays:
      '彩虹糖豆只能由烹饪产生，烹饪配方为：至少含有 1 个蜂王浆，没有不可食用度和怪物度，优先级为 12，需要花费 50 秒，每次烹饪产出 3 个。',
    waysQuery: ['蜂王浆', '怪物度', '不可食用度'],
    code: '"jellybean"',
    style: { objectFit: 'cover' },
    description: '食用彩虹糖豆可以在 2 分钟内每 2 秒恢复 2 生命值，加上及时效果一共恢复 122 生命值',
  },
  {
    id: 'Kabobs_Dropped',
    name: 'Kabobs',
    cname: '肉串',
    imgPath: '/images/cooking/Kabobs_Dropped.webp',
    temperatureType: FoodTemperatureEnum.Hot,
    foodType: FoodTypeEnum.Meat,
    dimension: [37.5, 3, 5],
    expired: 15,
    getWays:
      '肉串只能由烹饪产生。制作配方为：至少有 1 个树枝，肉度大于 0，怪物度和不可食用度小于等于 1。优先级为 5，需要花费 40 秒。',
    waysQuery: ['树枝', '肉度', '怪物度', '不可食用度'],
    code: '"kabobs"',
  },
  {
    id: 'Leafy_Meatloaf_Dropped',
    name: 'Leafy Meatloaf',
    cname: '叶肉糕',
    imgPath: '/images/cooking/Leafy_Meatloaf_Dropped.webp',
    foodType: FoodTypeEnum.Meat,
    dimension: [37.5, 8, 5],
    expired: 20,
    getWays: '叶肉糕只能由烹饪产生，烹饪配方为：至少有 2 个叶肉/烤叶肉，优先级为 25，需要花费 40 秒。',
    waysQuery: ['叶肉/烤叶肉'],
    code: '	"leafloaf"',
  },
  {
    id: 'Lobster_Bisque_Dropped',
    name: 'Lobster Bisque',
    cname: '龙虾浓汤',
    imgPath: '/images/cooking/Lobster_Bisque_Dropped.webp',
    foodType: FoodTypeEnum.Meat,
    dimension: [25, 60, 10],
    expired: 10,
    getWays: '龙虾汤只能由烹饪产生。烹饪配方为：至少 1 个龙虾，冰度大于 0。优先级为 30，需要花费 10 秒。',
    waysQuery: ['龙虾', '冰度'],
    code: '"lobsterbisque"',
    style: { objectFit: 'cover' },
  },
  {
    id: 'Lobster_Dinner_Dropped',
    name: 'Lobster Dinner',
    cname: '龙虾正餐',
    imgPath: '/images/cooking/Lobster_Dinner_Dropped.webp',
    foodType: FoodTypeEnum.Meat,
    expired: 15,
    dimension: [37.5, 60, 50],
    getWays:
      '龙虾正餐只能由烹饪产生。烹饪配方为：至少 1 只龙虾，至少 1 块黄油，肉度大于等于 1，鱼度大于等于 1，不能有冰度。优先级为 25，需要花费 20 秒来烹饪。',
    waysQuery: ['龙虾', '黄油', '肉度', '鱼度', '冰度'],
    code: '"lobsterdinner"',
    style: { objectFit: 'cover' },
  },
  {
    id: 'Mandrake_Soup_Dropped',
    name: 'Mandrake Soup',
    cname: '曼德草拉汤',
    imgPath: '/images/cooking/Mandrake_Soup_Dropped.webp',
    foodType: FoodTypeEnum.Veggie,
    expired: 6,
    dimension: [150, 100, 5],
    getWays: '曼德拉草汤只能由烹饪产生。烹饪配方为：至少有 1 个曼德拉草。优先级为 10，需要花费 60 秒。',
    waysQuery: ['曼德拉草'],
    code: '"mandrakesoup"',
  },
  {
    id: 'Meatballs_Dropped',
    name: 'Meatballs',
    cname: '肉丸',
    imgPath: '/images/cooking/Meatballs_Dropped.webp',
    foodType: FoodTypeEnum.Meat,
    dimension: [62.5, 3, 5],
    expired: 10,
    getWays: '肉丸只能由烹饪产生。烹饪配方为：肉度大于 0，没有不可食用度。优先级为 -1，需要花费 15 秒。',
    waysQuery: ['肉度', '不可食用度'],
    code: '"meatballs"',
  },
  {
    id: 'Meaty_Stew_Dropped',
    name: 'Meaty Stew',
    cname: '肉汤',
    imgPath: '/images/cooking/Meaty_Stew_Dropped.webp',
    dimension: [150, 12, 5],
    expired: 10,
    getWays: '炖肉汤只能由烹饪产生。烹饪配方为：肉度大于等于 3，没有不可食用度。优先级为 0，需要花费 15 秒。',
    waysQuery: ['肉度', '不可食用度'],
    code: '	"bonestew"',
  },
  {
    id: 'Melonsicle_Dropped',
    name: 'Melonsicle',
    cname: '西瓜冰棍',
    imgPath: '/images/cooking/Melonsicle_Dropped.webp',
    temperatureType: FoodTemperatureEnum.Cold,
    foodType: FoodTypeEnum.Veggie,
    dimension: [12.5, 3, 20],
    expired: 3,
    getWays:
      '西瓜冰棍只能由烹饪产生。烹饪配方为：至少 1 个西瓜，至少 1 个树枝，冰度大于 0，不包含肉度、蔬菜度、蛋度。优先级为 10，需要花费 10 秒。',
    waysQuery: ['西瓜', '冰度', '树枝', '冰度', '肉度', '蔬菜度', '蛋度'],
    code: '"watermelonicle"',
    style: { maxWidth: '80%' },
  },
  {
    id: 'Milkmade_Hat_Dropped',
    name: 'Milkmade Hat',
    cname: '牛奶帽',
    imgPath: '/images/cooking/Milkmade_Hat_Dropped.webp',
    dimension: ['+3.90625/5秒', '-1.33/分钟', 0],
    expired: 4,
    getWays:
      '牛奶帽只能由烹饪产生。烹饪配方为：至少有 1 个裸露鼻孔和 1 个海带叶，乳制品度大于等于 1。优先级为 55，需要花费 40 秒。',
    waysQuery: ['裸露鼻孔', '海带叶', '乳制品'],
    code: '	"batnosehat"',
    description:
      '牛奶帽只有在装备时才会开始腐烂，脱下时停止腐烂，腐烂后直接消失。通过装备牛奶帽，玩家可共计恢复 187.5 饥饿值，并损失 5.3 理智值',
  },
  {
    id: 'Monster_Lasagna_Dropped',
    name: 'Monster Lasagna',
    cname: '怪物千层饼',
    imgPath: '/images/cooking/Monster_Lasagna_Dropped.webp',
    foodType: [FoodTypeEnum.Meat, FoodTypeEnum.Monster],
    dimension: [37.5, -20, -20],
    expired: 6,
    getWays: '怪物千层饼可以由烹饪产生。烹饪配方为：怪物度大于等于 2，没有不可食用度。优先级为 10，需要花费 10 秒。',
    waysQuery: ['怪物度', '不可食用度'],
    code: '"monsterlasagna"',
    style: { objectFit: 'cover' },
  },
  {
    id: 'Monster_Tartare_Dropped',
    name: 'Monster Tartare',
    cname: '怪物鞑靼',
    imgPath: '/images/cooking/Monster_Tartare_Dropped.webp',
    dimension: [62.5, -20, -20],
    foodType: [FoodTypeEnum.Meat, FoodTypeEnum.Monster],
    expired: 10,
    getWays:
      '怪物鞑靼属于大厨特色菜，只能由沃利使用便携烹饪锅烹饪，配方为：怪物度大于等于 2，没有不可食用度。优先级为 30，需要花费 10 秒，但由于便携烹饪锅减少 20% 烹饪时间，实际烹饪时间为 8 秒。',
    waysQuery: ['大厨特色菜', '沃利', '怪物度', '便携烹饪锅', '不可食用度'],
    code: '"monstertartare"',
    style: { objectFit: 'cover' },
  },
  {
    id: 'Moqueca_Dropped',
    name: 'Moqueca',
    cname: '海鲜杂烩',
    imgPath: '/images/cooking/Moqueca_Dropped.webp',
    foodType: FoodTypeEnum.Meat,
    dimension: [112.5, 60, 33],
    expired: 8,
    getWays:
      '海鲜杂烩属于大厨特色菜，只能由沃利使用便携烹饪锅烹饪，配方为：至少有 1 个番茄/烤番茄，至少有 1 个洋葱/烤洋葱，鱼度大于 0，不能有不可食用度。优先级为 30，需要花费 40 秒，但由于便携烹饪锅减少 20% 烹饪时间，实际烹饪时间为 32 秒。',
    waysQuery: ['大厨特色菜', '沃利', '便携烹饪锅', '番茄/烤番茄', '洋葱/烤洋葱', '鱼度', '不可食用度'],
    code: '"moqueca"',
    style: { objectFit: 'cover' },
  },
  {
    id: 'Mushy_Cake_Dropped',
    name: 'Mushy Cake',
    cname: '蘑菇蛋糕',
    imgPath: '/images/cooking/Mushy_Cake_Dropped.webp',
    dimension: [25, 0, 10],
    foodType: FoodTypeEnum.Goodies,
    expired: 15,
    getWays:
      '蘑菇蛋糕只能由烹饪产生。烹饪配方为：采摘的红色、绿色、蓝色三种蘑菇各 1 个，月亮蘑菇 1 个（注意：所有材料均不可用烤熟的版本替代），优先级为 30，需要花费 20 秒。',
    waysQuery: ['红色', '绿色', '蓝色', '月亮蘑菇'],
    code: '"shroomcake"',
    description: '食用蘑菇蛋糕后: 清零催眠值，催眠抗性提升10点，只需 1 天，在 30 秒内完全免疫催眠。',
  },
  {
    id: 'Pierogi_dropped',
    name: 'Pierogi',
    cname: '波兰水饺',
    imgPath: '/images/cooking/Pierogi_dropped.webp',
    foodType: FoodTypeEnum.Meat,
    expired: 20,
    dimension: [37.5, 40, 5],
    getWays:
      '波兰水饺只能由烹饪产生。烹饪配方为：肉度大于 0，蛋度大于 0，蔬菜度大于等于 0.5，没有不可食用度。优先级为 5 ，需要花费 20 秒。',
    waysQuery: ['肉度', '蛋度', '蔬菜度', '不可食用度'],
    code: '"perogies"',
    style: { objectFit: 'cover' },
  },
  {
    id: 'Plain_Omelette_Dropped',
    name: 'Plain Omelette',
    cname: '普通煎蛋',
    imgPath: '/images/cooking/Plain_Omelette_Dropped.webp',
    dimension: [50, 3, 3],
    foodType: FoodTypeEnum.Meat,
    expired: 10,
    getWays: '普通煎蛋只能烹饪产生。烹饪配方为：蛋度大于等于 3。优先级为 0，需要花费 10 秒。',
    waysQuery: ['蛋度'],
    code: '"justeggs"',
  },
  {
    id: 'Powdercake_Dropped',
    name: 'Powdercake',
    cname: '粉末蛋糕',
    imgPath: '/images/cooking/Powdercake_Dropped.webp',
    foodType: FoodTypeEnum.Veggie,
    dimension: [0, -3, 0],
    expired: 18750,
    getWays:
      '粉末蛋糕只能由烹饪产生。烹饪配方为：至少 1 个玉米/爆米花/爆米花鱼/玉米鳕鱼、至少 1 个蜂蜜、至少 1 个树枝。优先级为 10，需要花费 10 秒。',
    waysQuery: ['玉米', '爆米花', '爆米花鱼', '玉米鳕鱼', '蜂蜜', '树枝'],
    code: '"powcake"',
  },
  {
    id: 'Puffed_Potato_Soufflé_Dropped',
    name: 'Puffed Potato Soufflé',
    cname: '蓬松土豆奶酥',
    imgPath: '/images/cooking/Puffed_Potato_Soufflé_Dropped.webp',
    foodType: FoodTypeEnum.Veggie,
    dimension: [37.5, 20, 15],
    expired: 10,
    getWays:
      '蓬松土豆蛋奶酥属于大厨特色菜，只能由沃利使用便携烹饪锅烹饪，配方为：至少有 2 个土豆/烤土豆，蛋度大于 0，不能有肉度、不可食用度。优先级为 30，需要花费 40 秒，但由于便携烹饪锅减少 20% 烹饪时间，实际烹饪时间为 32 秒。',
    waysQuery: ['大厨特色菜', '沃利', '便携烹饪锅', '土豆/烤土豆', '蛋度', '不可食用度', '肉度'],
    code: '"potatosouffle"',
  },
  {
    id: 'Pumpkin_Cookies_Dropped',
    name: 'Pumpkin Cookies',
    cname: '南瓜饼干',
    imgPath: '/images/cooking/Pumpkin_Cookies_Dropped.webp',
    dimension: [37.5, 0, 15],
    foodType: FoodTypeEnum.Veggie,
    expired: 10,
    getWays:
      '南瓜饼干可以由烹饪产生。烹饪配方为：至少有 1 个南瓜/烤南瓜，甜味剂度大于等于 2。优先级为 10，需要花费 40 秒。',
    waysQuery: ['南瓜/烤南瓜', '甜味剂度'],
    code: '"pumpkincookie"',
  },
  {
    id: 'Ratatouille_Dropped',
    name: 'Ratatouille',
    cname: '蔬菜杂烩',
    imgPath: '/images/cooking/Ratatouille_Dropped.webp',
    foodType: FoodTypeEnum.Veggie,
    dimension: [25, 3, 5],
    expired: 15,
    getWays:
      '蔬菜杂烩只能由烹饪产生。烹饪配方为：蔬菜度大于等于 0.5，没有肉度、不可食用度。优先级为 0，需要花费 20 秒。',
    waysQuery: ['蔬菜度', '肉度', '不可食用度'],
    code: '"ratatouille"',
  },
  {
    id: 'Salsa_Fresca_Dropped',
    name: 'Salsa Fresca',
    cname: '生鲜萨尔萨酱',
    imgPath: '/images/cooking/Salsa_Fresca_Dropped.webp',
    foodType: FoodTypeEnum.Veggie,
    dimension: [25, 3, 33],
    expired: 15,
    getWays:
      '生鲜萨尔萨酱只能由烹饪产生。烹饪配方为：至少 1 个番茄/烤番茄，至少 1 个洋葱/烤洋葱，没有蛋度、肉度和不可食用度。优先级为 20，需要花费 10 秒。',
    waysQuery: ['番茄/烤番茄', '洋葱/烤洋葱', '蛋度', '肉度', '不可食用度'],
    code: '"salsa"',
  },
  {
    id: 'Seafood_Gumbo_Dropped',
    name: 'Seafood Gumbo',
    cname: '海鲜浓汤',
    imgPath: '/images/cooking/Seafood_Gumbo_Dropped.webp',
    dimension: [37.5, 40, 20],
    foodType: FoodTypeEnum.Meat,
    expired: 10,
    getWays: '海鲜浓汤只能由烹饪产生。烹饪配方为：鱼度大于 2。优先级为 10，需要花费 20 秒。',
    waysQuery: ['鱼度'],
    code: '"seafoodgumbo"',
    style: { objectFit: 'cover' },
  },
  {
    id: 'Soothing_Tea_Dropped',
    name: 'Soothing Tea',
    cname: '舒缓茶',
    imgPath: '/images/cooking/Soothing_Tea_Dropped.webp',
    temperatureType: FoodTemperatureEnum.Hot,
    foodType: FoodTypeEnum.Generic,
    dimension: [0, 3, 15],
    expired: 3,
    getWays:
      '舒缓茶只能由烹饪产生。烹饪配方为：至少 1 个必忘我，甜味剂度大于 0，冰度大于 0，不能有怪物度、蔬菜度、肉度、鱼度、蛋度、油脂度、乳制品度、不可食用度。优先级为 1，需要花费 20 秒。',
    waysQuery: [
      '必忘我',
      '甜味剂度',
      '冰度',
      '蔬菜度',
      '鱼度',
      '蛋度',
      '油脂度',
      '乳制品度',
      '怪物度',
      '不可食用度',
      '肉度',
    ],
    code: '"sweettea"',
    description: '食用舒缓茶可以在 60 秒内每 2 秒恢复 1 理智值，加上及时效果一共恢复 45 理智值。',
  },
  {
    id: 'Spicy_Chili_Dropped',
    name: 'Spicy Chili',
    cname: '辣椒炖肉',
    imgPath: '/images/cooking/Spicy_Chili_Dropped.webp',
    temperatureType: FoodTemperatureEnum.Hot,
    foodType: FoodTypeEnum.Meat,
    dimension: [37.5, 20, 0],
    getWays: '辣椒炖肉只能由烹饪产生。烹饪配方为：肉度大于等于 1.5，蔬菜度大于等于 1.5，优先级为 10，需要花费 10 秒。',
    waysQuery: ['肉度', '蔬菜度'],
    code: '"hotchili"',
  },
  {
    id: 'Steamed_Twigs_Dropped',
    name: 'Steamed Twigs',
    cname: '蒸树枝',
    imgPath: '/images/cooking/Steamed_Twigs_Dropped.webp',
    foodType: [FoodTypeEnum.Roughage, FoodTypeEnum.Wood],
    dimension: [100, 15, 0],
    expired: 20,
    getWays:
      '蒸树枝只能由烹饪产生。烹饪配方为：不可食用度大于 0，没有怪物度、肉度、鱼度、蛋度、油脂度、乳制品度和魔法度。优先级为 -5，需要花费 10 秒。',
    waysQuery: ['蔬菜度', '鱼度', '蛋度', '油脂度', '乳制品度', '怪物度', '不可食用度', '肉度', '魔法度'],
    code: '"beefalofeed"',
  },
  {
    id: 'Stuffed_Eggplant_Dropped',
    name: 'Stuffed Eggplant',
    cname: '酿茄子',
    imgPath: '/images/cooking/Stuffed_Eggplant_Dropped.webp',
    temperatureType: FoodTemperatureEnum.Hot,
    foodType: FoodTypeEnum.Veggie,
    dimension: [37.5, 3, 6],
    expired: 15,
    getWays: '酿茄子只能由烹饪产生，烹饪配方为：至少有 1 个茄子/烤茄子，蔬菜度大于 1。优先级为 1，需要花费 40 秒。',
    waysQuery: ['蔬菜度', '茄子/烤茄子'],
    code: 'stuffedeggplant',
  },
  {
    id: 'Stuffed_Fish_Heads_Dropped',
    name: 'Stuffed Fish Heads',
    cname: '酿鱼头',
    imgPath: '/images/cooking/Stuffed_Fish_Heads_Dropped.webp',
    foodType: FoodTypeEnum.Meat,
    dimension: [75, 20, 0],
    expired: 3,
    getWays:
      '酿鱼头只能由烹饪产生。烹饪配方为：至少有 1 个藤壶/熟藤壶，鱼度大于等于 1.25。优先级为 26，需要花费 40 秒。',
    waysQuery: ['鱼度', '藤壶/熟藤壶'],
    code: 'barnaclestuffedfishhead',
    style: { objectFit: 'cover' },
  },
  {
    id: 'Stuffed_Night_Cap_Dropped',
    name: 'Stuffed Night Cap',
    cname: '酿夜帽',
    imgPath: '/images/cooking/Stuffed_Night_Cap_Dropped.webp',
    dimension: [18.75, -20, -15],
    foodType: FoodTypeEnum.Meat,
    expired: 15,
    getWays: '酿夜帽只能由烹饪产生。烹饪配方为：至少 2 个月亮蘑菇，至少 1 个怪物肉。优先级为 30，需要花费 20 秒。',
    waysQuery: ['月亮蘑菇', '怪物肉'],
    code: '"shroombait"',
    description: '食用酿夜帽会给食用者增加 10 点催眠值，催眠时间为 20 秒。',
  },
  {
    id: 'Stuffed_Pepper_Poppers_Dropped',
    name: 'Stuffed Pepper Poppers',
    cname: '爆炒填馅辣椒',
    imgPath: '/images/cooking/Stuffed_Pepper_Poppers_Dropped.webp',
    temperatureType: FoodTemperatureEnum.Hot,
    foodType: FoodTypeEnum.Meat,
    dimension: [25, 30, -5],
    expired: 15,
    getWays:
      '爆炒填馅辣椒只能由烹饪产生。烹饪配方为：至少有 1 个辣椒/烤辣椒，肉度大于 0 小于等于 1.5，没有不可食用度。优先级为 20，需要花费 40 秒。',
    waysQuery: ['辣椒/烤辣椒', '肉度', '不可食用度'],
    code: 'pepperpopper',
    style: { objectFit: 'cover' },
  },
  {
    id: 'Surf_n_Turf_Dropped',
    name: 'Surf n Turf',
    cname: '海鲜牛排',
    imgPath: '/images/cooking/Surf_n_Turf_Dropped.webp',
    dimension: [37.5, 60, 33],
    expired: 10,
    getWays:
      '海鲜牛排只能由烹饪产生。烹饪配方为：肉度大于等于 2.5，鱼度大于等于 1.5，不能有冰度。优先级为 30，需要花费 20 秒。',
    waysQuery: ['肉度', '鱼度', '冰度'],
    code: '"surfnturf"',
    style: { objectFit: 'cover' },
  },
  {
    id: 'Taffy_Dropped',
    name: 'Taffy',
    cname: '太妃糖',
    imgPath: '/images/cooking/Taffy_Dropped.webp',
    dimension: [25, -3, 15],
    foodType: FoodTypeEnum.Goodies,
    expired: 15,
    getWays: '太妃糖只能由烹饪产生，制作配方为：甜味剂度大于等于 3，没有肉度。优先级为 10，需要花费 40 秒。',
    waysQuery: ['甜味剂度', '肉度'],
    code: '"taffy"',
  },
  {
    id: 'Tall_Scotch_Eggs_Dropped',
    name: 'Tall Scotch Eggs',
    cname: '苏格兰高脚鸟蛋',
    imgPath: '/images/cooking/Tall_Scotch_Eggs_Dropped.webp',
    dimension: [150, 60, 5],
    expired: 15,
    getWays:
      '苏格兰高鸟蛋只能由烹饪产生。烹饪配方为：至少有 1 个高脚鸟蛋，蔬菜度大于等于 1。优先级为 10 ，需要花费 40 秒。',
    waysQuery: ['高脚鸟蛋', '蔬菜度'],
    code: '"talleggs"',
  },
  {
    id: 'Trail_Mix_Dropped',
    name: 'Trail Mix',
    cname: '什锦干果',
    imgPath: '/images/cooking/Trail_Mix_Dropped.webp',
    dimension: [12.5, 30, 5],
    foodType: FoodTypeEnum.Veggie,
    expired: 15,
    getWays:
      '什锦干果只能由烹饪产生。烹饪配方为：至少 1 个桦栗果/烤桦栗果，至少 1 个浆果/烤浆果/多汁浆果/烤多汁浆果，种子度大于等于 1，水果度大于等于 1，不包含肉度、蔬菜度、蛋度、乳制品度。优先级为 10，需要花费 10 秒。',
    waysQuery: [
      '桦栗果',
      '烤桦栗果',
      '浆果',
      '烤浆果',
      '多汁浆果',
      '烤多汁浆果',
      '种子度',
      '水果度',
      '肉度',
      '蔬菜度',
      '蛋度',
      '乳制品度',
    ],
    code: '"trailmix"',
  },
  {
    id: 'Turkey_Dinner_Dropped',
    name: 'Turkey Dinner',
    cname: '火鸡正餐',
    imgPath: '/images/cooking/Turkey_Dinner_Dropped.webp',
    temperatureType: FoodTemperatureEnum.Hot,
    foodType: FoodTypeEnum.Meat,
    dimension: [75, 20, 5],
    expired: 6,
    getWays:
      '火鸡正餐能由烹饪产生。烹饪配方为：至少有 2 个鸟腿，肉度大于 1，蔬菜度大于等于 0.5 或者水果度大于 0。优先级为 10，需要花费 60 秒。',
    waysQuery: ['鸟腿', '肉度', '蔬菜度', '水果度'],
    code: '"turkeydinner"',
  },
  {
    id: 'Unagi_Dropped',
    name: 'Unagi',
    cname: '鳗鱼料理',
    imgPath: '/images/cooking/Unagi_Dropped.webp',
    dimension: [37.5, 20, 5],
    foodType: FoodTypeEnum.Meat,
    expired: 10,
    getWays:
      '鳗鱼料理只能由烹饪产生。烹饪配方为：至少 1 个鳗鱼/活鳗鱼/烤鳗鱼，至少 1 个苔藓/海带叶/熟海带叶/干海带叶。优先级为 20，需要花费 10 秒。',
    waysQuery: ['鳗鱼/活鳗鱼/烤鳗鱼', '苔藓', '海带叶', '熟海带叶', '干海带叶'],
    code: '"unagi"',
    style: { objectFit: 'cover' },
  },
  {
    id: 'Vegetable_Stinger_Dropped',
    name: 'Vegetable Stinger',
    cname: '蔬菜鸡尾酒',
    imgPath: '/images/cooking/Vegetable_Stinger_Dropped.webp',
    dimension: [25, 3, 33],
    foodType: FoodTypeEnum.Veggie,
    expired: 15,
    getWays:
      '蔬菜鸡尾酒只能由烹饪产生。烹饪配方为：至少 1 个番茄/烤番茄/芦笋/烤芦笋，冰度大于 0，蔬菜度大于 2，不包含肉度、蛋度和不可食用度。优先级为 15，需要花费 10 秒。',
    waysQuery: ['番茄', '烤番茄', '芦笋', '烤芦笋', '冰度', '蔬菜度', '肉度', '蛋度', '不可食用度'],
    code: '"vegstinger"',
  },
  {
    id: 'Veggie_Burger_Dropped',
    name: 'Veggie Burger',
    cname: '蔬菜堡',
    imgPath: '/images/cooking/Veggie_Burger_Dropped.webp',
    dimension: [37.5, 30, 33],
    foodType: FoodTypeEnum.Meat,
    expired: 6,
    getWays:
      '素食堡只能由烹饪产生。烹饪配方为：至少有 1 个叶肉/烤叶肉，至少有 1 个洋葱/烤洋葱，蔬菜度大于等于 2，优先级为 26，需要花费 40 秒。',
    waysQuery: ['叶肉', '烤叶肉', '洋葱/烤洋葱', '蔬菜度'],
    code: '"leafymeatburger"',
    style: { objectFit: 'cover' },
  },
  {
    id: 'Volt_Goat_Chaud-Froid_Dropped',
    name: 'Volt Goat Chaud-Froid',
    cname: '伏特羊肉冻',
    imgPath: '/images/cooking/Volt_Goat_Chaud-Froid_Dropped.webp',
    dimension: [37.5, 3, 10],
    foodType: FoodTypeEnum.Goodies,
    expired: 10,
    getWays:
      '伏特羊肉冻属于大厨特色菜，它只能由沃利使用便携烹饪锅烹饪，配方为：至少 1 个伏特羊角，甜味剂度大于等于 2 。优先级为 30，需要花费 40 秒，但由于便携烹饪锅减少 20% 烹饪时间，实际烹饪时间为 32 秒。',
    waysQuery: ['大厨特色菜', '沃利', '便携烹饪锅', '伏特羊角', '甜味剂度'],
    code: '"voltgoatjelly"',
    style: { objectFit: 'cover' },
    description: '角色或生物食用伏特羊肉冻后，所有攻击都将具有带电标签，持续 5 分钟。',
  },
  {
    id: 'Waffles_Dropped',
    name: 'Waffles',
    cname: '华夫饼',
    imgPath: '/images/cooking/Waffles_Dropped.webp',
    dimension: [37.5, 60, 5],
    foodType: FoodTypeEnum.Veggie,
    expired: 6,
    getWays:
      '华夫饼只能由烹饪产生。烹饪配方为：至少 1 个黄油，至少 1 个浆果/烤浆果/多汁浆果/烤多汁浆果，蛋度大于 0。优先级为 10，需要花费 10 秒。',
    waysQuery: ['黄油', '浆果/烤浆果/多汁浆果/烤多汁浆果', '蛋度'],
    code: '"waffles"',
    style: { objectFit: 'cover' },
  },
  {
    id: 'Wet_Goop_Dropped',
    name: 'Wet Goop',
    cname: '潮湿黏糊',
    imgPath: '/images/cooking/Wet_Goop_Dropped.webp',
    dimension: [0, 0, 0],
    foodType: FoodTypeEnum.Generic,
    expired: 6,
    getWays:
      '由烹饪产生。其优先级是全游戏最低的 -10，所以当所有其它料理的烹饪条件全部不符合时才会产出。烹饪潮湿黏糊需要 10 秒',
    code: '"wetgoop"',
  },
];
